(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "cask")
(depends-on "dtrt-indent")
(depends-on "ecb")
(depends-on "emmet-mode")
(depends-on "expand-region")
(depends-on "highlight-parentheses")
(depends-on "iy-go-to-char")
(depends-on "key-chord")
(depends-on "lively")
(depends-on "melpa")
(depends-on "mic-paren")
(depends-on "minimap")
(depends-on "multiple-cursors")
(depends-on "nsis-mode")
(depends-on "org")
(depends-on "org-bullets")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "paredit-everywhere")
(depends-on "paredit-menu")
(depends-on "popwin")
(depends-on "pos-tip")
(depends-on "redshank")
(depends-on "undo-tree")
(depends-on "wgrep")
(depends-on "yasnippet")
(depends-on "zenburn-theme")