(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")

(depends-on "cask")
(depends-on "cedet")
(depends-on "ecb")
(depends-on "emmet-mode")
(depends-on "highlight-parentheses")
(depends-on "melpa")
(depends-on "mic-paren")
(depends-on "nsis-mode")
(depends-on "org")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "paredit-everywhere")
(depends-on "paredit-menu")
(depends-on "redshank")
(depends-on "semantic")
(depends-on "wgrep")
(depends-on "yasnippet")