(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(LaTeX-Omega-command "xelatex")
 '(TeX-Omega-mode t)
 '(TeX-PDF-mode t)
 '(TeX-output-view-style
   (quote
    (("^dvi$"
      ("^landscape$" "^pstricks$\\|^pst-\\|^psfrag$")
      "%(o?)dvips -t landscape %d -o && gv %f")
     ("^dvi$" "^pstricks$\\|^pst-\\|^psfrag$" "%(o?)dvips %d -o && gv %f")
     ("^dvi$"
      ("^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "^landscape$")
      "%(o?)xdvi %dS -paper a4r -s 0 %d")
     ("^dvi$" "^a4\\(?:dutch\\|paper\\|wide\\)\\|sem-a4$" "%(o?)xdvi %dS -paper a4 %d")
     ("^dvi$"
      ("^a5\\(?:comb\\|paper\\)$" "^landscape$")
      "%(o?)xdvi %dS -paper a5r -s 0 %d")
     ("^dvi$" "^a5\\(?:comb\\|paper\\)$" "%(o?)xdvi %dS -paper a5 %d")
     ("^dvi$" "^b5paper$" "%(o?)xdvi %dS -paper b5 %d")
     ("^dvi$" "^letterpaper$" "%(o?)xdvi %dS -paper us %d")
     ("^dvi$" "^legalpaper$" "%(o?)xdvi %dS -paper legal %d")
     ("^dvi$" "^executivepaper$" "%(o?)xdvi %dS -paper 7.25x10.5in %d")
     ("^dvi$" "." "%(o?)xdvi %dS %d")
     ("^pdf$" "." "evince %o")
     ("^html?$" "." "netscape %o"))))
 '(confirm-kill-emacs (quote y-or-n-p))
 '(custom-enabled-themes (quote (zenburn)))
 '(custom-safe-themes
   (quote
    ("11636897679ca534f0dec6f5e3cb12f28bf217a527755f6b9e744bd240ed47e1" "dd0c53e873e23298716844777306ab88685278d4d5547efb0bd3f10b50cffef7" "9370aeac615012366188359cb05011aea721c73e1cb194798bc18576025cabeb" "1177fe4645eb8db34ee151ce45518e47cc4595c3e72c55dc07df03ab353ad132" "4c9ba94db23a0a3dea88ee80f41d9478c151b07cb6640b33bfc38be7c2415cc4" "3ad55e40af9a652de541140ff50d043b7a8c8a3e73e2a649eb808ba077e75792" default)))
 '(ecb-layout-window-sizes nil)
 '(ecb-options-version "2.32")
 '(ecb-show-node-info-in-minibuffer
   (quote
    ((always . path)
     (always . name)
     (always . path)
     (always . name+type))))
 '(ecb-tip-of-the-day nil)
 '(ecb-tree-buffer-style (quote image))
 '(ediff-diff-options "")
 '(fast-lock-minimum-size 2000)
 '(fci-rule-color "#383838")
 '(file-cache-assoc-function (quote assoc-ignore-case))
 '(font-lock-beginning-of-syntax-function nil t)
 '(font-lock-keywords-case-fold-search nil t)
 '(font-lock-keywords-only nil t)
 '(font-lock-mark-block-function nil t)
 '(font-lock-maximum-decoration t)
 '(fringe-mode 10 nil (fringe))
 '(highlight-completion-list-external (quote (t t t t t t t t t t)))
 '(highlight-wrong-size-font nil t)
 '(icomplete-minibuffer-setup-hook
   (quote
    ((lambda nil
       (make-local-variable
        (quote max-mini-window-height))
       (setq max-mini-window-height 3)))))
 '(icomplete-mode t)
 '(ido-auto-merge-work-directories-length -1)
 '(ido-confirm-unique-completion t)
 '(ido-create-new-buffer (quote always))
 '(ido-default-buffer-method (quote selected-window))
 '(ido-default-file-method (quote selected-window))
 '(image-file-name-extensions
   (quote
    ("png" "jpeg" "jpg" "gif" "tiff" "tif" "xbm" "xpm" "pbm" "pgm" "ppm" "pnm" "svg" "pdf")))
 '(imaxima-scale-factor 1.0)
 '(imaxima-use-maxima-mode-flag t)
 '(indent-tabs-mode nil)
 '(indicate-empty-lines t)
 '(inferior-lisp-program "sbcl")
 '(ispell-dictionary "en_GB" t)
 '(ispell-program-name "/usr/bin/hunspell")
 '(line-number-display-limit-width 1000)
 '(longlines-show-hard-newlines t)
 '(main-line-color1 "#222912")
 '(main-line-color2 "#09150F")
 '(msb-mode t)
 '(msf-abbrev-indent-after-expansion t)
 '(msf-abbrev-root "/home/mathrick/elisp/mode-abbrevs")
 '(pabbrev-global-mode-excluded-modes
   (quote
    (shell-mode custom-mode dired-mode telnet-mode c-mode)))
 '(pabbrev-global-mode-not-buffer-names (quote ("*Messages*")))
 '(pabbrev-idle-timer-verbose nil)
 '(package-selected-packages
   (quote
    (sly use-package counsel swiper git commander zenburn-theme yasnippet wgrep weechat web-beautify undo-tree smartparens redshank pyenv-mode puppet-mode pungi pos-tip popwin php-mode paredit-menu paredit-everywhere paradox pallet ox-gfm org-bullets org omnisharp nsis-mode multiple-cursors minimap mic-paren magit-filenotify lively key-chord iy-go-to-char highlight-parentheses groovy-mode expand-region emmet-mode ecb dtrt-indent diff-hl cython-mode company)))
 '(paradox-github-token t)
 '(paren-dont-load-timer nil)
 '(paren-dont-touch-blink nil)
 '(paren-sexp-mode (quote mismatch))
 '(pascal-auto-lineup (quote (all)))
 '(pascal-auto-newline nil)
 '(pascal-tab-always-indent t)
 '(powerline-color1 "#222912")
 '(powerline-color2 "#09150F")
 '(preview-LaTeX-command
   (quote
    ("%`%l \"\\nonstopmode\\nofiles\\PassOptionsToPackage{"
     ("," . preview-required-option-list)
     "}{preview}\\AtBeginDocument{\\ifx\\ifPreview\\undefined" preview-default-preamble "\\fi}\"%' %t")))
 '(preview-required-option-list
   (quote
    ("active" "tightpage" "auctex"
     (preview-preserve-counters "counters")
     "pdftex")))
 '(py-imenu-show-method-args-p t)
 '(recentf-mode t)
 '(redshank-accessor-name-function (quote redshank-accessor-name/%))
 '(redshank-canonical-slot-name-function (quote redshank-canonical-slot-name/%))
 '(rw-hunspell-default-dictionary "en_GB")
 '(rw-hunspell-dicpath-list (quote ("/usr/share/hunspell" "/usr/share/myspell")))
 '(rw-hunspell-make-dictionary-menu t)
 '(rw-hunspell-use-rw-ispell t)
 '(safe-local-variable-values
   (quote
    ((js-indent-level . 4)
     (encoding . utf-8)
     (package . F2CL)
     (Package . F2CL)
     (Package . Maxima)
     (Package . containers)
     (Package . LINJ)
     (pbook-monochrome . t)
     (pbook-style . article)
     (pbook-use-toc . t)
     (pbook-author . "Luke Gorrie, with modifications by Paul Khuong")
     (Package . CCL)
     (indent-tabs)
     (Encoding . utf-8)
     (show-trailing-whitespace . t)
     (Readtable . GLISP)
     (Package . SGML)
     (Package . LALR)
     (Package . DRAKMA)
     (Package . metabang\.moptilities)
     (Package . CXML)
     (readtable . runes)
     (Package . computed-class)
     (Package . CL-INTERPOL)
     (Package . CLIMACS-JAVA-SYNTAX)
     (Package . CLIMACS-GUI)
     (Package . CLIMACS-C-SYNTAX)
     (Package . CLIMACS-LISP-SYNTAX)
     (Package . CLIMACS)
     (Package . CLIMACS-COMMANDS)
     (Package . COMMON-LISP-USER)
     (Package . CLIMACS-PROLOG-SYNTAX)
     (Package . DREI-LISP-SYNTAX)
     (Package . DREI-SYNTAX)
     (Package . CLIM-POSTSCRIPT)
     (Package . CLIM-CLX)
     (Lowercase . T)
     (Package . Xlib)
     (Log . clx\.log)
     (Package . AUTOMATON)
     (Package . GOATEE)
     (Package . CLIMI)
     (readtable . py-ast-user-readtable)
     (package . clpython)
     (readtable . py-user-readtable)
     (package . clpython\.parser)
     (readtable . py-ast-readtable)
     (Package . bind)
     (syntax . ANSI-COMMON-LISP)
     (Package SERIES :use "COMMON-LISP" :colon-mode :external)
     (Package . CHUNGA)
     (Package . FLEXI-STREAMS)
     (package . puri)
     (syntax . COMMON-LISP)
     (Package ITERATE :use "COMMON-LISP" :colon-mode :external)
     (Package . DREI-COMMANDS)
     (Package . clim-internals)
     (Package . DREI)
     (Package . DREI-EDITING)
     (Package . User)
     (Package . MCCLIM-FREETYPE)
     (Package . ESA)
     (Package . CLIM-INTERNALS)
     (Indent-tabs-mode . NIL)
     (movitz-mode . t)
     (Package . CL-PPCRE)
     (Syntax . ANSI-Common-Lisp)
     (Syntax . Common-lisp)
     (Package . XLIB)
     (Lowercase . Yes)
     (Syntax . Common-Lisp)
     (py-indent-offset . 4)
     (Package . CL-USER)
     (Package . HUNCHENTOOT)
     (package . net\.html\.generator)
     (unibyte . t)
     (Syntax . COMMON-LISP)
     (Package . CL-WHO)
     (Base . 10))))
 '(save-abbrevs nil)
 '(save-place t nil (saveplace))
 '(scroll-preserve-screen-position t)
 '(select-enable-clipboard t)
 '(semanticdb-global-mode t nil (semantic/db))
 '(server-done-hook (quote ((lambda nil (delete-frame)))))
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(skk-henkan-show-candidates-keys (quote (48 49 50 51 52 53 54 55 56 57 \.\.\.)))
 '(skk-server-host nil t)
 '(skk-server-inhibit-startup-server t)
 '(skk-server-prog nil)
 '(skk-show-inline t t)
 '(slime-autodoc-use-multiline-p t)
 '(slime-complete-symbol*-fancy t)
 '(slime-enable-evaluate-in-emacs t)
 '(split-width-threshold 360)
 '(srecode-insert-ask-variable-method (quote ask))
 '(tool-bar-mode nil)
 '(tooltip-gud-modes (quote (gud-mode c-mode c++-mode pascal-mode)))
 '(tooltip-gud-tips-p nil)
 '(tooltip-use-echo-area nil)
 '(truncate-lines t)
 '(undo-limit 200000)
 '(undo-strong-limit 300000)
 '(uniquify-buffer-name-style (quote post-forward-angle-brackets) nil (uniquify))
 '(uniquify-trailing-separator-p nil)
 '(vc-annotate-background "#2b2b2b")
 '(vc-annotate-color-map
   (quote
    ((20 . "#bc8383")
     (40 . "#cc9393")
     (60 . "#dfaf8f")
     (80 . "#d0bf8f")
     (100 . "#e0cf9f")
     (120 . "#f0dfaf")
     (140 . "#5f7f5f")
     (160 . "#7f9f7f")
     (180 . "#8fb28f")
     (200 . "#9fc59f")
     (220 . "#afd8af")
     (240 . "#bfebbf")
     (260 . "#93e0e3")
     (280 . "#6ca0a3")
     (300 . "#7cb8bb")
     (320 . "#8cd0d3")
     (340 . "#94bff3")
     (360 . "#dc8cc3"))))
 '(vc-annotate-very-old-color "#dc8cc3")
 '(vc-diff-switches (quote ("-u")))
 '(viper-keep-point-on-repeat nil)
 '(wdired-enable t)
 '(wdired-use-interactive-rename nil)
 '(which-function-mode nil)
 '(windmove-wrap-around t)
 '(x-symbol-initialize nil)
 '(yas/use-menu (quote abbreviate))
 '(yas/wrap-around-region (quote cua)))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#3F3F3F" :foreground "#DCDCCC" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 105 :width normal :foundry "unci" :family "monofur for Powerline")))))
